name: Mod Runs Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Minecraft Tests
      uses: Geometrically/fabric-test-runner@v1
      with:
        minecraftVersion: 1.15.2
